version: 2
jobs:
  conda:
    docker:
      - image: frolvlad/alpine-miniconda3
    steps:
      - run: apk add --no-cache build-base ca-certificates git openssh
      - checkout
      - restore_cache:
          keys:
            - conda-pkgs
      - run: conda env create
      - save_cache:
          key: conda-pkgs
          paths:
            - /opt/conda/pkgs
      - run: source activate xndframes && python setup.py develop
      - run: source activate xndframes && py.test --junitxml=test-reports/junit.xml --cov=./
workflows:
  version: 2
  test:
    jobs:
      - conda