name: xndframes-docs
channels:
  - conda-forge
  - xnd/label/dev
dependencies:
  - coverage
  - flake8
  - ipython
  - matplotlib
  - numpy
  - numpydoc
  - pandas >=0.23.0
  - pytest
  - pytest-cov
  - python=3.6
  - sphinx
  - sphinx_rtd_theme
  - xnd
  - gumath
